events:
  test1:
    time: '00:00'
    before: '&e60&f초 후 &c핫타임 &f아이템이 지급됩니다.'
    after: '&c핫타임 &f아이템을 지급하였습니다.'
    commands:
      - 'say example reward'

  breaktime:
    time: '12:30'
    before: ''
    after: '&d깜짝 이벤트!'
    commands:
      - 'say event2'